name: plot-ecg
channels:
    - conda-forge
    - anaconda
    - defaults
dependencies:
    - python=3.8
    - pip
    - numpy
    - pandas
    - matplotlib
    - ipympl
    - h5py
    - bs4
    - lxml
    - tqdm
